### PR TITLE
Add: a configurable delay before the popover is triggered

### PR DESCRIPTION
**Pull request by benkoshy**
What is the PR?

* Adds a pause before the fetch action is triggered.

I hope this helps. I can add some documentation if required in another PR.

### CODE REVIEW

**Comment by guillaumebriday** [comment]
Why would we want to do that @benkoshy? 👍

**Comment by benkoshy** [comment]
On  a page full of triggers,  most would be needlessly triggered

**Comment by chakraskun** [comment]
+1 for this, just to avoid to trigger when user move the mouse around

**Comment by guillaumebriday** [comment]
If you still think it's relevant, please reopen a PR in the main monorepo: https://github.com/stimulus-components/stimulus-components

**Pull request closed without merging**
